# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ry

# 挂载目录
VOLUME /home/ry
# 创建目录
RUN mkdir -p /home/ry
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/*.jar /home/ry/ry-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","ry-gateway.jar"]